### PR TITLE
add well-known ASPNET.Core log scopes

### PR DESCRIPTION
**Pull request by ArXa1L**

### CODE REVIEW

**Comment by kungasc** [comment]
What about https://github.com/vostok/applications.aspnetcore/blob/master/Vostok.Applications.AspNetCore/Helpers/MicrosoftConstants.cs?

**Comment by kungasc** [comment]
Also should not be placed in Commons folder.
Move to `Helpers/MicrosoftLogScopes`.

**Comment by ArXa1L** [comment]
> What about https://github.com/vostok/applications.aspnetcore/blob/master/Vostok.Applications.AspNetCore/Helpers/MicrosoftConstants.cs?

I am using `vostok.logging.ms` library but i don't use `vostok.applications.aspnetcore` library yet.
Should i copy `*Old` scopes from `vostok.applications.aspnetcore`?

**Comment by kungasc** [comment]
> > What about https://github.com/vostok/applications.aspnetcore/blob/master/Vostok.Applications.AspNetCore/Helpers/MicrosoftConstants.cs?
> 
> I am using `vostok.logging.ms` library but i don't use `vostok.applications.aspnetcore` library yet.
> Should i copy `*Old` scopes from `vostok.applications.aspnetcore`?

Yes, and remove same constants from `Applications.AspNetCore` module.

**Pull request merged**
